import type { Locale } from '@/stores/locale'
import { uiMessages } from '@/locales/ui'

export type RoutePath =
  | '/'
  | '/ffxiv'
  | '/ffxiv/glamour'
  | '/ffxiv/glamour/template'
  | '/ffxiv/glamour/equipinfo'
  | '/ffxiv/plate'
  | '/ffxiv/armoire'
  | '/silence'
  | '/silence/angel'
  | '/silence/glitch'
  | '/about'

export interface NavItem {
  id: string
  labelKey: string
  commandKey?: string
  route: RoutePath
  variant?: 'default' | 'primary'
}

export interface SiteCategory {
  id: string
  titleKey: string
  shortTitleKey: string
  kickerKey: string
  descriptionKey: string
  route: RoutePath
}

export interface ToolEntry {
  id: string
  titleKey: string
  projectName: string
  route: RoutePath
  summaryKey: string
  sourcePath: string
  apiBase?: string
  devPort?: number
  statusLabelKey: string
}

export interface SilenceGroupEntry {
  id: 'angel' | 'glitch'
  titleKey: string
  route: RoutePath
  summaryKey: string
  statusLabelKey: string
}

export interface SiteLocaleOption {
  locale: Locale
  labelKey: string
  commandKey: string
}

export const textKeys = {
  placeholder: 'common.placeholder',
  back: 'common.back',
  enter: 'common.enter',
  children: 'common.children',
  closeMenu: 'common.close.menu',
  closeConfig: 'common.close.config',
  itemsUnit: 'common.items.unit',
  layersUnit: 'common.layers.unit',
  notSelected: 'common.notSelected',
  noAssets: 'common.noAssets',
  selectPreset: 'common.selectPreset',
  nsplateSearchPresets: 'nsplate.search.presets',
  nsplateSearchAssets: 'nsplate.search.assets',
  nsplateSearchNoResults: 'nsplate.search.noResults',
  nsplateClearSearch: 'nsplate.search.clear',
  previousPreset: 'common.previousPreset',
  nextPreset: 'common.nextPreset',
  check: 'common.check',
  checking: 'common.checking',
  api: 'common.api',
  project: 'common.project',
  port: 'common.port',
  health: 'common.health',
  import: 'common.import',
  export: 'common.export',
  save: 'common.save',
  saveDraft: 'common.saveDraft',
  open: 'common.open',
  details: 'common.details',
  status: 'common.status',
  toolbar: 'common.toolbar',
  tabs: 'common.tabs',
  primaryNavigation: 'common.primaryNavigation',
  siteZhName: 'site.name.zh',
  siteEnName: 'site.name.en',
  siteTitle: 'site.title',
  siteDescription: 'site.description',
  menu: 'site.nav.menu',
  menuCommand: 'site.nav.menuCommand',
  menuCategory: 'site.nav.menuCategory',
  homeCommand: 'site.nav.homeCommand',
  config: 'site.nav.config',
  configCommand: 'site.nav.configCommand',
  about: 'site.nav.about',
  aboutCommand: 'site.nav.aboutCommand',
  silenceCommand: 'site.nav.silenceCommand',
  home: 'site.nav.home',
  menuTitle: 'site.window.menuTitle',
  configTitle: 'site.window.configTitle',
  themeMode: 'site.theme.mode',
  day: 'site.theme.day',
  dayCommand: 'site.theme.dayCommand',
  night: 'site.theme.night',
  nightCommand: 'site.theme.nightCommand',
  languageMode: 'site.language.mode',
  localeZhLabel: 'site.locale.zh.label',
  localeJaLabel: 'site.locale.ja.label',
  localeKoLabel: 'site.locale.ko.label',
  localeEnLabel: 'site.locale.en.label',
  localeZhCommand: 'site.locale.zh.command',
  localeJaCommand: 'site.locale.ja.command',
  localeKoCommand: 'site.locale.ko.command',
  localeEnCommand: 'site.locale.en.command',
  statusOpen: 'site.status.open',
  statusWip: 'site.status.wip',
  silence: 'site.menu.silence',
  oc: 'site.menu.oc',
  silenceAngel: 'silence.group.angel.title',
  silenceGlitch: 'silence.group.glitch.title',
  silenceCharacterProfile: 'silence.character.profile',
  silenceCharacterVisual: 'silence.character.visual',
  silenceCharacterArchive: 'silence.character.archive',
  silenceCharacterNotes: 'silence.character.notes',
  silenceCharacterNavigation: 'silence.character.navigation',
  silenceCharacterMissing: 'silence.character.missing',
  silenceCharacterSections: 'silence.character.sections',
  silenceCharacterBasicProfile: 'silence.character.basicProfile',
  silenceCharacterWorlds: 'silence.character.worlds',
  silenceCharacterGallery: 'silence.character.gallery',
  silenceCharacterRelationships: 'silence.character.relationships',
  silenceCharacterSpoiler: 'silence.character.spoiler',
  silenceCharacterPreview: 'silence.character.preview',
  silenceCharacterColor: 'silence.character.color',
  silenceCharacterDraftStatus: 'silence.character.draftStatus',
  silenceCharacterForms: 'silence.character.forms',
  ffxivWorkshop: 'ffxiv.workshop.title',
  ffxivWorkshopShort: 'ffxiv.workshop.short',
  glamourTitle: 'ffxiv.tool.glamour.title',
  plateTitle: 'ffxiv.tool.plate.title',
  armoireTitle: 'ffxiv.tool.armoire.title',
  ffxivTermReviewTitle: 'ffxiv.termReview.title',
  ffxivTermReviewKicker: 'ffxiv.termReview.kicker',
  ffxivTermReviewLead: 'ffxiv.termReview.lead',
  ffxivTermReviewFilters: 'ffxiv.termReview.filters',
  ffxivTermReviewSearch: 'ffxiv.termReview.search',
  ffxivTermReviewSearchPlaceholder: 'ffxiv.termReview.search.placeholder',
  ffxivTermReviewModule: 'ffxiv.termReview.module',
  ffxivTermReviewStatus: 'ffxiv.termReview.status',
  ffxivTermReviewSource: 'ffxiv.termReview.source',
  ffxivTermReviewAll: 'ffxiv.termReview.all',
  ffxivTermReviewSummary: 'ffxiv.termReview.summary',
  ffxivTermReviewVisible: 'ffxiv.termReview.visible',
  ffxivTermReviewTotal: 'ffxiv.termReview.total',
  ffxivTermReviewNeedsCheck: 'ffxiv.termReview.needsCheck',
  ffxivTermReviewColumnTerm: 'ffxiv.termReview.column.term',
  ffxivTermReviewColumnValues: 'ffxiv.termReview.column.values',
  ffxivTermReviewColumnStatus: 'ffxiv.termReview.column.status',
  ffxivTermReviewColumnSource: 'ffxiv.termReview.column.source',
  ffxivTermReviewColumnNote: 'ffxiv.termReview.column.note',
  ffxivTermReviewLegacy: 'ffxiv.termReview.legacy',
  ffxivTermReviewComposedFrom: 'ffxiv.termReview.composedFrom',
  ffxivTermReviewMissingValue: 'ffxiv.termReview.missingValue',
  ffxivTermReviewStatusConfirmed: 'ffxiv.termReview.status.confirmed',
  ffxivTermReviewStatusNeedsCheck: 'ffxiv.termReview.status.needsCheck',
  ffxivTermReviewStatusLayout: 'ffxiv.termReview.status.layout',
  ffxivTermReviewSourceGameCsv: 'ffxiv.termReview.source.gameCsv',
  ffxivTermReviewSourceLegacyLayout: 'ffxiv.termReview.source.legacyLayout',
  ffxivTermReviewSourceUserConfirmed: 'ffxiv.termReview.source.userConfirmed',
  ffxivTermReviewSourceSiteUi: 'ffxiv.termReview.source.siteUi',
  nsarmoireImport: 'nsarmoire.panel.import',
  nsarmoireOverview: 'nsarmoire.panel.overview',
  nsarmoireDistribution: 'nsarmoire.panel.distribution',
  nsarmoireInsights: 'nsarmoire.panel.insights',
  nsarmoireCatalogGrid: 'nsarmoire.panel.catalogGrid',
  nsarmoireValidation: 'nsarmoire.panel.validation',
  nsarmoireCabinetProgress: 'nsarmoire.panel.cabinetProgress',
  nsarmoireGlamourSetProgress: 'nsarmoire.panel.glamourSetProgress',
  nsarmoireDyeRisk: 'nsarmoire.panel.dyeRisk',
  nsarmoireIdenticalModels: 'nsarmoire.panel.identicalModels',
  nsarmoireActionHints: 'nsarmoire.panel.actionHints',
  nsarmoireCharacterProfile: 'nsarmoire.panel.characterProfile',
  nsarmoireSectionNavigation: 'nsarmoire.section.navigation',
  nsarmoireSectionRailCollapse: 'nsarmoire.section.rail.collapse',
  nsarmoireSectionRailExpand: 'nsarmoire.section.rail.expand',
  nsarmoireSectionCleanup: 'nsarmoire.section.cleanup',
  nsarmoireSectionCleanupShort: 'nsarmoire.section.cleanup.short',
  nsarmoireSectionCollection: 'nsarmoire.section.collection',
  nsarmoireSectionCollectionShort: 'nsarmoire.section.collection.short',
  nsarmoireSectionCharacters: 'nsarmoire.section.characters',
  nsarmoireSectionCharactersShort: 'nsarmoire.section.characters.short',
  nsarmoireSectionActions: 'nsarmoire.section.actions',
  nsarmoireSectionStorage: 'nsarmoire.section.storage',
  nsarmoireSectionReference: 'nsarmoire.section.reference',
  nsarmoireSectionCatalogData: 'nsarmoire.section.catalogData',
  nsarmoireCollectionLoading: 'nsarmoire.section.collection.loading',
  nsarmoireCollectionStoreStats: 'nsarmoire.collection.storeStats',
  nsarmoireCollectionCabinetStats: 'nsarmoire.collection.cabinetStats',
  nsarmoireCollectionGlamourSetStats: 'nsarmoire.collection.glamourSetStats',
  nsarmoireCollectionCatalog: 'nsarmoire.collection.catalog',
  nsarmoireCollectionNeedsCatalog: 'nsarmoire.collection.needsCatalog',
  nsarmoireCollectionNoItems: 'nsarmoire.collection.noItems',
  nsarmoireCollectionStatusStored: 'nsarmoire.collection.status.stored',
  nsarmoireCollectionStatusMissing: 'nsarmoire.collection.status.missing',
  nsarmoireCollectionStatusTransferable: 'nsarmoire.collection.status.transferable',
  nsarmoireCollectionStatusOwned: 'nsarmoire.collection.status.owned',
  nsarmoireCollectionStatusUnowned: 'nsarmoire.collection.status.unowned',
  nsarmoireCollectionStatusDyed: 'nsarmoire.collection.status.dyed',
  nsarmoireCabinetStatsSummary: 'nsarmoire.collection.cabinet.summary',
  nsarmoireCabinetTransferableTitle: 'nsarmoire.collection.cabinet.transferable',
  nsarmoireCabinetMissingTitle: 'nsarmoire.collection.cabinet.missing',
  nsarmoireGlamourSetStatsSummary: 'nsarmoire.collection.glamourSet.summary',
  nsarmoireGlamourSetNoSets: 'nsarmoire.collection.glamourSet.empty',
  nsarmoireGlamourSetPieces: 'nsarmoire.collection.glamourSet.pieces',
  nsarmoireGlamourSetComplete: 'nsarmoire.collection.glamourSet.complete',
  nsarmoireGlamourSetIncomplete: 'nsarmoire.collection.glamourSet.incomplete',
  nsarmoireGlamourSetNotStored: 'nsarmoire.collection.glamourSet.notStored',
  nsarmoireStoreOutfits: 'nsarmoire.panel.storeOutfits',
  nsarmoireStoreSummary: 'nsarmoire.store.summary',
  nsarmoireStoreMetricLabel: 'nsarmoire.store.metric.label',
  nsarmoireStoreMetricTotal: 'nsarmoire.store.metric.total',
  nsarmoireStoreMetricMapped: 'nsarmoire.store.metric.mapped',
  nsarmoireStoreMetricDetected: 'nsarmoire.store.metric.detected',
  nsarmoireStoreMetricPartial: 'nsarmoire.store.metric.partial',
  nsarmoireStoreMetricNeedsMapping: 'nsarmoire.store.metric.needsMapping',
  nsarmoireStoreSearchLabel: 'nsarmoire.store.search.label',
  nsarmoireStoreSearchPlaceholder: 'nsarmoire.store.search.placeholder',
  nsarmoireStoreFilterLabel: 'nsarmoire.store.filter.label',
  nsarmoireStoreFilterAll: 'nsarmoire.store.filter.all',
  nsarmoireStoreTagsLabel: 'nsarmoire.store.tags.label',
  nsarmoireStoreTagNpcCostume: 'nsarmoire.store.tag.npcCostume',
  nsarmoireStoreTagBonusCostume: 'nsarmoire.store.tag.bonusCostume',
  nsarmoireStoreTagCollectorEditionBonus: 'nsarmoire.store.tag.collectorEditionBonus',
  nsarmoireStoreTagReplicaCostume: 'nsarmoire.store.tag.replicaCostume',
  nsarmoireStoreTagFanFestivalCostume: 'nsarmoire.store.tag.fanFestivalCostume',
  nsarmoireStoreTagCrossoverCostume: 'nsarmoire.store.tag.crossoverCostume',
  nsarmoireStoreTagMoonfireFaire: 'nsarmoire.store.tag.moonfireFaire',
  nsarmoireStoreTagHatchingTide: 'nsarmoire.store.tag.hatchingTide',
  nsarmoireStoreTagTheRising: 'nsarmoire.store.tag.theRising',
  nsarmoireStoreTagStarlightCelebration: 'nsarmoire.store.tag.starlightCelebration',
  nsarmoireStoreTagValentioneDay: 'nsarmoire.store.tag.valentioneDay',
  nsarmoireStoreTagLittleLadiesDay: 'nsarmoire.store.tag.littleLadiesDay',
  nsarmoireStoreTagAllSaintsWake: 'nsarmoire.store.tag.allSaintsWake',
  nsarmoireStoreTagHeavensturn: 'nsarmoire.store.tag.heavensturn',
  nsarmoireStoreTagGoldSaucerFestival: 'nsarmoire.store.tag.goldSaucerFestival',
  nsarmoireStoreGroupSeasonal: 'nsarmoire.store.group.seasonal',
  nsarmoireStoreGroupOther: 'nsarmoire.store.group.other',
  nsarmoireStoreDetailTagMaleOnly: 'nsarmoire.store.detailTag.maleOnly',
  nsarmoireStoreDetailTagFemaleOnly: 'nsarmoire.store.detailTag.femaleOnly',
  nsarmoireStoreStatusComplete: 'nsarmoire.store.status.complete',
  nsarmoireStoreStatusPartial: 'nsarmoire.store.status.partial',
  nsarmoireStoreStatusMissing: 'nsarmoire.store.status.missing',
  nsarmoireStoreStatusNeedsMapping: 'nsarmoire.store.status.needsMapping',
  nsarmoireStoreRegionCn: 'nsarmoire.store.region.cn',
  nsarmoireStoreRegionGlobal: 'nsarmoire.store.region.global',
  nsarmoireStoreRegionTw: 'nsarmoire.store.region.tw',
  nsarmoireStoreRegionKr: 'nsarmoire.store.region.kr',
  nsarmoireStoreLinkCn: 'nsarmoire.store.link.cn',
  nsarmoireStoreLinkGlobal: 'nsarmoire.store.link.global',
  nsarmoireStoreLinkTw: 'nsarmoire.store.link.tw',
  nsarmoireStoreLinkKr: 'nsarmoire.store.link.kr',
  nsarmoireStoreOpenLink: 'nsarmoire.store.openLink',
  nsarmoireStoreNoLink: 'nsarmoire.store.noLink',
  nsarmoireStoreNoPrice: 'nsarmoire.store.noPrice',
  nsarmoireStoreItemsLabel: 'nsarmoire.store.items.label',
  nsarmoireStorePieceLocation: 'nsarmoire.store.piece.location',
  nsarmoireStorePieceDye: 'nsarmoire.store.piece.dye',
  nsarmoireStorePieceBind: 'nsarmoire.store.piece.bind',
  nsarmoireStorePieceBound: 'nsarmoire.store.piece.bound',
  nsarmoireStorePieceUnbound: 'nsarmoire.store.piece.unbound',
  nsarmoireStorePieceMoreEntries: 'nsarmoire.store.piece.moreEntries',
  nsarmoireStoreNoItems: 'nsarmoire.store.items.empty',
  nsarmoireStoreEmpty: 'nsarmoire.store.empty',
  nsarmoireStoreCatalogLoading: 'nsarmoire.store.catalog.loading',
  nsarmoireStoreCatalogError: 'nsarmoire.store.catalog.error',
  nsarmoireStoreCatalogRetry: 'nsarmoire.store.catalog.retry',
  nsarmoireStoreReviewTitle: 'nsarmoire.storeReview.title',
  nsarmoireStoreReviewSummary: 'nsarmoire.storeReview.summary',
  nsarmoireStoreReviewFilterAll: 'nsarmoire.storeReview.filter.all',
  nsarmoireStoreReviewFilterPendingCorrection: 'nsarmoire.storeReview.filter.pendingCorrection',
  nsarmoireStoreReviewFilterCorrected: 'nsarmoire.storeReview.filter.corrected',
  nsarmoireStoreReviewFilterNeedsMapping: 'nsarmoire.storeReview.filter.needsMapping',
  nsarmoireStoreReviewFilterMissingLinks: 'nsarmoire.storeReview.filter.missingLinks',
  nsarmoireStoreReviewFilterEdited: 'nsarmoire.storeReview.filter.edited',
  nsarmoireStoreReviewOutfitColumn: 'nsarmoire.storeReview.column.outfit',
  nsarmoireStoreReviewItemsColumn: 'nsarmoire.storeReview.column.items',
  nsarmoireStoreReviewLinksColumn: 'nsarmoire.storeReview.column.links',
  nsarmoireStoreReviewStateColumn: 'nsarmoire.storeReview.column.state',
  nsarmoireStoreReviewRegionCn: 'nsarmoire.storeReview.region.cn',
  nsarmoireStoreReviewRegionGlobal: 'nsarmoire.storeReview.region.global',
  nsarmoireStoreReviewRegionTw: 'nsarmoire.storeReview.region.tw',
  nsarmoireStoreReviewRegionKr: 'nsarmoire.storeReview.region.kr',
  nsarmoireStoreReviewLinkPlaceholder: 'nsarmoire.storeReview.link.placeholder',
  nsarmoireStoreReviewPricePlaceholder: 'nsarmoire.storeReview.price.placeholder',
  nsarmoireStoreReviewCopyPatch: 'nsarmoire.storeReview.action.copyPatch',
  nsarmoireStoreReviewDownloadPatch: 'nsarmoire.storeReview.action.downloadPatch',
  nsarmoireStoreReviewResetDraft: 'nsarmoire.storeReview.action.resetDraft',
  nsarmoireStoreReviewOpenLink: 'nsarmoire.storeReview.action.openLink',
  nsarmoireStoreReviewConfirmCorrected: 'nsarmoire.storeReview.action.confirmCorrected',
  nsarmoireStoreReviewUnconfirmCorrected: 'nsarmoire.storeReview.action.unconfirmCorrected',
  nsarmoireStoreReviewExclude: 'nsarmoire.storeReview.action.exclude',
  nsarmoireStoreReviewUnexclude: 'nsarmoire.storeReview.action.unexclude',
  nsarmoireStoreReviewPatchCopied: 'nsarmoire.storeReview.status.patchCopied',
  nsarmoireStoreReviewPatchCopyFailed: 'nsarmoire.storeReview.status.patchCopyFailed',
  nsarmoireStoreReviewNoChanges: 'nsarmoire.storeReview.status.noChanges',
  nsarmoireStoreReviewChangedCount: 'nsarmoire.storeReview.status.changedCount',
  nsarmoireStoreReviewStatusPendingCorrection: 'nsarmoire.storeReview.status.pendingCorrection',
  nsarmoireStoreReviewStatusCorrected: 'nsarmoire.storeReview.status.corrected',
  nsarmoireStoreReviewStatusExcluded: 'nsarmoire.storeReview.status.excluded',
  nsarmoireStoreReviewTagsLabel: 'nsarmoire.storeReview.tags.label',
  nsarmoireStoreReviewDetailTagsLabel: 'nsarmoire.storeReview.detailTags.label',
  nsarmoireStoreReviewTagFilterLabel: 'nsarmoire.storeReview.tagFilter.label',
  nsarmoireStoreReviewTagFilterAll: 'nsarmoire.storeReview.tagFilter.all',
  nsarmoireStoreReviewTagFilterTagged: 'nsarmoire.storeReview.tagFilter.tagged',
  nsarmoireStoreReviewTagFilterUntagged: 'nsarmoire.storeReview.tagFilter.untagged',
  nsarmoireStoreReviewAddItemLabel: 'nsarmoire.storeReview.item.add.label',
  nsarmoireStoreReviewAddItemPlaceholder: 'nsarmoire.storeReview.item.add.placeholder',
  nsarmoireStoreReviewAddItem: 'nsarmoire.storeReview.item.add.action',
  nsarmoireStoreReviewRemoveItem: 'nsarmoire.storeReview.item.remove.action',
  nsarmoireStoreReviewCandidateItems: 'nsarmoire.storeReview.item.candidates',
  nsarmoireStoreReviewCandidateAdd: 'nsarmoire.storeReview.item.candidateAdd',
  nsarmoireStoreReviewCandidateAddPieces: 'nsarmoire.storeReview.item.candidateAddPieces',
  nsarmoireStoreReviewCandidatePieceCount: 'nsarmoire.storeReview.item.candidatePieceCount',
  nsarmoireStoreReviewItemAdded: 'nsarmoire.storeReview.item.added',
  nsarmoireStoreReviewItemNotFound: 'nsarmoire.storeReview.item.notFound',
  nsarmoireStoreReviewItemDuplicate: 'nsarmoire.storeReview.item.duplicate',
  nsarmoireStoreReviewItemDraft: 'nsarmoire.storeReview.item.draft',
  nsarmoireStoreReviewNoItems: 'nsarmoire.storeReview.empty.items',
  nsarmoireStoreReviewNoResults: 'nsarmoire.storeReview.empty.results',
  nsarmoireRecommendationCabinet: 'nsarmoire.recommendation.cabinet',
  nsarmoireRecommendationSets: 'nsarmoire.recommendation.sets',
  nsarmoireRecommendationSetPieces: 'nsarmoire.recommendation.setPieces',
  nsarmoireRecommendationTradableItems: 'nsarmoire.recommendation.tradableItems',
  nsarmoireRecommendationCrafterGathererReplicas:
    'nsarmoire.recommendation.crafterGathererReplicas',
  nsarmoireRecommendationDuplicateItems: 'nsarmoire.recommendation.duplicateItems',
  nsarmoireRecommendationDuplicates: 'nsarmoire.recommendation.duplicates',
  nsarmoireRecommendationDyes: 'nsarmoire.recommendation.dyes',
  nsarmoireSummaryInventory: 'nsarmoire.summary.inventory',
  nsarmoireSummaryStorage: 'nsarmoire.summary.storage',
  nsarmoireSummaryDyeWarning: 'nsarmoire.summary.dyeWarning',
  nsarmoireSummaryNoDyeWarning: 'nsarmoire.summary.noDyeWarning',
  nsarmoireHintCabinetSummary: 'nsarmoire.hint.cabinet.summary',
  nsarmoireHintCabinetNone: 'nsarmoire.hint.cabinet.none',
  nsarmoireHintSetsSummary: 'nsarmoire.hint.sets.summary',
  nsarmoireHintSetsNone: 'nsarmoire.hint.sets.none',
  nsarmoireHintSetPiecesSummary: 'nsarmoire.hint.setPieces.summary',
  nsarmoireHintDyed: 'nsarmoire.hint.dyed',
  nsarmoireHintValuableDyeDeferredSuffix: 'nsarmoire.hint.valuableDyeDeferredSuffix',
  nsarmoireHintTradableItemsSummary: 'nsarmoire.hint.tradableItems.summary',
  nsarmoireHintTradableItemsNone: 'nsarmoire.hint.tradableItems.none',
  nsarmoireHintTradableUnbound: 'nsarmoire.hint.tradableEntry.unbound',
  nsarmoireHintReplicaRecycleSummary: 'nsarmoire.hint.replicaRecycle.summary',
  nsarmoireHintReplicaRecycleNone: 'nsarmoire.hint.replicaRecycle.none',
  nsarmoireHintReplicaRecycleReward: 'nsarmoire.hint.replicaRecycle.reward',
  nsarmoireHintReplicaRecycleDyes: 'nsarmoire.hint.replicaRecycle.dyes',
  nsarmoireHintReplicaRecycleNoReturnedDyes: 'nsarmoire.hint.replicaRecycle.noReturnedDyes',
  nsarmoireHintDuplicateItemsSummary: 'nsarmoire.hint.duplicateItems.summary',
  nsarmoireHintDuplicateItemsNone: 'nsarmoire.hint.duplicateItems.none',
  nsarmoireHintDuplicatesSummary: 'nsarmoire.hint.duplicates.summary',
  nsarmoireHintDuplicatesNone: 'nsarmoire.hint.duplicates.none',
  nsarmoireHintDyesSummary: 'nsarmoire.hint.dyes.summary',
  nsarmoireHintDyesPreserved: 'nsarmoire.hint.dyes.preserved',
  nsarmoireHintAllClearTitle: 'nsarmoire.hint.allClear.title',
  nsarmoireHintAllClearMessage: 'nsarmoire.hint.allClear.message',
  nsarmoireHintCatalogPendingTitle: 'nsarmoire.hint.catalogPending.title',
  nsarmoireHintCatalogPendingMessage: 'nsarmoire.hint.catalogPending.message',
  nsarmoireHintMoreItems: 'nsarmoire.hint.moreItems',
  nsarmoireHintMissingPieces: 'nsarmoire.hint.missingPieces',
  nsarmoireStatusStored: 'nsarmoire.status.stored',
  nsarmoireStatusUnstored: 'nsarmoire.status.unstored',
  nsarmoireStatusFoundOutsideSet: 'nsarmoire.status.foundOutsideSet',
  nsarmoireHintOwnedEntries: 'nsarmoire.hint.ownedEntries',
  nsarmoireHintDuplicateEntryLocation: 'nsarmoire.hint.duplicateEntry.location',
  nsarmoireHintDuplicateEntryDyes: 'nsarmoire.hint.duplicateEntry.dyes',
  nsarmoireHintCurrentLocation: 'nsarmoire.hint.currentLocation',
  nsarmoireHintNamedLocations: 'nsarmoire.hint.namedLocations',
  nsarmoireExpandList: 'nsarmoire.action.expandList',
  nsarmoireCollapseList: 'nsarmoire.action.collapseList',
  nsarmoireLoadMoreList: 'nsarmoire.action.loadMoreList',
  nsarmoireLoadExampleSnapshot: 'nsarmoire.action.loadExampleSnapshot',
  nsarmoireImportSnapshot: 'nsarmoire.action.importSnapshot',
  nsarmoireClearSnapshot: 'nsarmoire.action.clearSnapshot',
  nsarmoireDownloadHelper: 'nsarmoire.action.downloadHelper',
  nsarmoireDownloadHelperShort: 'nsarmoire.action.downloadHelperShort',
  nsarmoireConnectHelper: 'nsarmoire.action.connectHelper',
  nsarmoireSelectHelperProcess: 'nsarmoire.action.selectHelperProcess',
  nsarmoireClearRetainerCache: 'nsarmoire.action.clearRetainerCache',
  nsarmoireShutdownHelper: 'nsarmoire.action.shutdownHelper',
  nsarmoireRefreshHelper: 'nsarmoire.action.refreshHelper',
  nsarmoireCatalogFilterLabel: 'nsarmoire.catalog.filter.label',
  nsarmoireCatalogFilterAll: 'nsarmoire.catalog.filter.all',
  nsarmoireCatalogFilterCabinet: 'nsarmoire.catalog.filter.cabinet',
  nsarmoireCatalogFilterDuplicateItems: 'nsarmoire.catalog.filter.duplicateItems',
  nsarmoireCatalogFilterDuplicateModels: 'nsarmoire.catalog.filter.duplicateModels',
  nsarmoireCatalogFilterDyed: 'nsarmoire.catalog.filter.dyed',
  nsarmoireCatalogFilterGlamourDresser: 'nsarmoire.catalog.filter.glamourDresser',
  nsarmoireCatalogFilterArmoire: 'nsarmoire.catalog.filter.armoire',
  nsarmoireCatalogSearchLabel: 'nsarmoire.catalog.search.label',
  nsarmoireCatalogSearchPlaceholder: 'nsarmoire.catalog.search.placeholder',
  nsarmoireCatalogSortLabel: 'nsarmoire.catalog.sort.label',
  nsarmoireCatalogSortRisk: 'nsarmoire.catalog.sort.risk',
  nsarmoireCatalogSortContainer: 'nsarmoire.catalog.sort.container',
  nsarmoireCatalogSortName: 'nsarmoire.catalog.sort.name',
  nsarmoireCatalogSortItemId: 'nsarmoire.catalog.sort.itemId',
  nsarmoireCatalogMetricLabel: 'nsarmoire.catalog.metric.label',
  nsarmoireCatalogMetricVisible: 'nsarmoire.catalog.metric.visible',
  nsarmoireCatalogMetricActionItems: 'nsarmoire.catalog.metric.actionItems',
  nsarmoireCatalogMetricDyed: 'nsarmoire.catalog.metric.dyed',
  nsarmoireCatalogMetricDuplicates: 'nsarmoire.catalog.metric.duplicates',
  nsarmoireCatalogGridSummary: 'nsarmoire.catalog.grid.summary',
  nsarmoireCatalogGridEmpty: 'nsarmoire.catalog.grid.empty',
  nsarmoireCatalogQuantity: 'nsarmoire.catalog.quantity',
  nsarmoireCatalogDyeNone: 'nsarmoire.catalog.dye.none',
  nsarmoireCatalogIconFallback: 'nsarmoire.catalog.iconFallback',
  nsarmoireValidationLead: 'nsarmoire.validation.lead',
  nsarmoireValidationTechnicalBadge: 'nsarmoire.validation.technicalBadge',
  nsarmoireValidationStatusTriggered: 'nsarmoire.validation.status.triggered',
  nsarmoireValidationStatusNotTriggered: 'nsarmoire.validation.status.notTriggered',
  nsarmoireValidationStatusWaitingCatalog: 'nsarmoire.validation.status.waitingCatalog',
  nsarmoireValidationEvidenceRule: 'nsarmoire.validation.evidence.rule',
  nsarmoireValidationEvidenceFields: 'nsarmoire.validation.evidence.fields',
  nsarmoireValidationEvidenceResult: 'nsarmoire.validation.evidence.result',
  nsarmoireValidationEvidenceLocations: 'nsarmoire.validation.evidence.locations',
  nsarmoireValidationEvidenceItem: 'nsarmoire.validation.evidence.item',
  nsarmoireValidationEvidenceItems: 'nsarmoire.validation.evidence.items',
  nsarmoireValidationEvidenceModelKey: 'nsarmoire.validation.evidence.modelKey',
  nsarmoireValidationEvidenceModels: 'nsarmoire.validation.evidence.models',
  nsarmoireValidationEvidenceCatalog: 'nsarmoire.validation.evidence.catalog',
  nsarmoireValidationEvidenceDyes: 'nsarmoire.validation.evidence.dyes',
  nsarmoireValidationEvidenceDyeReset: 'nsarmoire.validation.evidence.dyeReset',
  nsarmoireValidationDuplicateItemsRule: 'nsarmoire.validation.duplicateItems.rule',
  nsarmoireValidationDuplicateItemsHit: 'nsarmoire.validation.duplicateItems.hit',
  nsarmoireValidationDuplicateItemsNone: 'nsarmoire.validation.duplicateItems.none',
  nsarmoireValidationDuplicateItemsResult: 'nsarmoire.validation.duplicateItems.result',
  nsarmoireValidationIdenticalModelsRule: 'nsarmoire.validation.identicalModels.rule',
  nsarmoireValidationIdenticalModelsHit: 'nsarmoire.validation.identicalModels.hit',
  nsarmoireValidationIdenticalModelsNone: 'nsarmoire.validation.identicalModels.none',
  nsarmoireValidationIdenticalModelsPending: 'nsarmoire.validation.identicalModels.pending',
  nsarmoireValidationCabinetRule: 'nsarmoire.validation.cabinet.rule',
  nsarmoireValidationCabinetHit: 'nsarmoire.validation.cabinet.hit',
  nsarmoireValidationCabinetNone: 'nsarmoire.validation.cabinet.none',
  nsarmoireValidationCabinetPending: 'nsarmoire.validation.cabinet.pending',
  nsarmoireValidationCabinetCatalogHit: 'nsarmoire.validation.cabinet.catalogHit',
  nsarmoireValidationDyesRule: 'nsarmoire.validation.dyes.rule',
  nsarmoireValidationDyesHit: 'nsarmoire.validation.dyes.hit',
  nsarmoireValidationDyesNone: 'nsarmoire.validation.dyes.none',
  nsarmoireValidationDyesResult: 'nsarmoire.validation.dyes.result',
  nsarmoireDyeResetCabinet: 'nsarmoire.dyeReset.cabinet',
  nsarmoireDyeResetGlamourSetBasket: 'nsarmoire.dyeReset.glamourSetBasket',
  nsarmoireDyeResetPreservedStorage: 'nsarmoire.dyeReset.preservedStorage',
  nsarmoireDyePreferenceLabel: 'nsarmoire.dyePreference.label',
  nsarmoireDyeCategoryGeneral: 'nsarmoire.dyeCategory.general',
  nsarmoireDyeCategoryExtra1: 'nsarmoire.dyeCategory.extra1',
  nsarmoireDyeCategoryExtra2: 'nsarmoire.dyeCategory.extra2',
  nsarmoireDyeCategoryStoreSpecial: 'nsarmoire.dyeCategory.storeSpecial',
  nsarmoireDyePreferenceCategories: 'nsarmoire.dyePreference.categories',
  nsarmoireDyePreferenceStoreSpecial: 'nsarmoire.dyePreference.storeSpecial',
  nsarmoireSnapshotInput: 'nsarmoire.input.snapshot',
  nsarmoireSnapshotReady: 'nsarmoire.status.snapshotReady',
  nsarmoireSnapshotEmpty: 'nsarmoire.status.snapshotEmpty',
  nsarmoireSnapshotError: 'nsarmoire.status.snapshotError',
  nsarmoireSnapshotFileTooLarge: 'nsarmoire.error.fileTooLarge',
  nsarmoireSnapshotInvalidJson: 'nsarmoire.error.invalidJson',
  nsarmoireSnapshotInvalidRoot: 'nsarmoire.error.invalidRoot',
  nsarmoireSnapshotInvalidSchema: 'nsarmoire.error.invalidSchema',
  nsarmoireSnapshotInvalidSource: 'nsarmoire.error.invalidSource',
  nsarmoireSnapshotInvalidGeneratedAt: 'nsarmoire.error.invalidGeneratedAt',
  nsarmoireSnapshotInvalidItems: 'nsarmoire.error.invalidItems',
  nsarmoireSnapshotTooManyItems: 'nsarmoire.error.tooManyItems',
  nsarmoireSnapshotInvalidItem: 'nsarmoire.error.invalidItem',
  nsarmoireSnapshotInvalidItemId: 'nsarmoire.error.invalidItemId',
  nsarmoireSnapshotInvalidContainer: 'nsarmoire.error.invalidContainer',
  nsarmoireSnapshotInvalidQuantity: 'nsarmoire.error.invalidQuantity',
  nsarmoireSnapshotInvalidDyes: 'nsarmoire.error.invalidDyes',
  nsarmoireCatalogStatus: 'nsarmoire.status.catalogStatus',
  nsarmoireCatalogPending: 'nsarmoire.status.catalogPending',
  nsarmoireCatalogLoading: 'nsarmoire.status.catalogLoading',
  nsarmoireCatalogReady: 'nsarmoire.status.catalogReady',
  nsarmoireCatalogEmpty: 'nsarmoire.status.catalogEmpty',
  nsarmoireCatalogError: 'nsarmoire.status.catalogError',
  nsarmoireCatalogErrorWithDetail: 'nsarmoire.status.catalogErrorWithDetail',
  nsarmoireNoDyeRisk: 'nsarmoire.status.noDyeRisk',
  nsarmoireHelperIdle: 'nsarmoire.status.helperIdle',
  nsarmoireHelperConnecting: 'nsarmoire.status.helperConnecting',
  nsarmoireHelperReady: 'nsarmoire.status.helperReady',
  nsarmoireHelperGameNotFound: 'nsarmoire.status.helperGameNotFound',
  nsarmoireHelperDresserNotLoaded: 'nsarmoire.status.helperDresserNotLoaded',
  nsarmoireHelperMultipleProcesses: 'nsarmoire.status.helperMultipleProcesses',
  nsarmoireHelperError: 'nsarmoire.status.helperError',
  nsarmoireHelperIdleMessage: 'nsarmoire.status.helperIdle.message',
  nsarmoireHelperConnectingMessage: 'nsarmoire.status.helperConnecting.message',
  nsarmoireHelperReadyMessage: 'nsarmoire.status.helperReady.message',
  nsarmoireHelperGameNotFoundMessage: 'nsarmoire.status.helperGameNotFound.message',
  nsarmoireHelperDresserNotLoadedMessage: 'nsarmoire.status.helperDresserNotLoaded.message',
  nsarmoireHelperMultipleProcessesMessage: 'nsarmoire.status.helperMultipleProcesses.message',
  nsarmoireHelperErrorMessage: 'nsarmoire.status.helperError.message',
  nsarmoireProcessDialogTitle: 'nsarmoire.process.dialog.title',
  nsarmoireProcessDialogMessage: 'nsarmoire.process.dialog.message',
  nsarmoireProcessRefresh: 'nsarmoire.process.action.refresh',
  nsarmoireProcessSelect: 'nsarmoire.process.action.select',
  nsarmoireProcessName: 'nsarmoire.process.field.name',
  nsarmoireProcessPid: 'nsarmoire.process.field.pid',
  nsarmoireProcessWindowTitle: 'nsarmoire.process.field.windowTitle',
  nsarmoireProcessStartedAt: 'nsarmoire.process.field.startedAt',
  nsarmoireProcessStatus: 'nsarmoire.process.field.status',
  nsarmoireProcessNoWindowTitle: 'nsarmoire.process.empty.windowTitle',
  nsarmoireProcessNoStartedAt: 'nsarmoire.process.empty.startedAt',
  nsarmoireProcessNoProcesses: 'nsarmoire.process.empty.processes',
  nsarmoireProcessSelected: 'nsarmoire.process.status.selected',
  nsarmoireProcessReadable: 'nsarmoire.process.status.readable',
  nsarmoireProcessUnreadable: 'nsarmoire.process.status.unreadable',
  nsarmoireProcessError: 'nsarmoire.process.status.error',
  nsarmoireReloadCatalog: 'nsarmoire.action.reloadCatalog',
  nsarmoireMetricEntries: 'nsarmoire.metric.entries',
  nsarmoireMetricUniqueItems: 'nsarmoire.metric.uniqueItems',
  nsarmoireMetricTotalQuantity: 'nsarmoire.metric.totalQuantity',
  nsarmoireMetricDyedEntries: 'nsarmoire.metric.dyedEntries',
  nsarmoireMetricGlamourDresser: 'nsarmoire.metric.glamourDresser',
  nsarmoireMetricArmoire: 'nsarmoire.metric.armoire',
  nsarmoireMetricStored: 'nsarmoire.metric.stored',
  nsarmoireMetricStorable: 'nsarmoire.metric.storable',
  nsarmoireMetricTransferable: 'nsarmoire.metric.transferable',
  nsarmoireMetricMissing: 'nsarmoire.metric.missing',
  nsarmoireMetricStoredSets: 'nsarmoire.metric.storedSets',
  nsarmoireMetricAvailableSets: 'nsarmoire.metric.availableSets',
  nsarmoireMetricIncompleteSets: 'nsarmoire.metric.incompleteSets',
  nsarmoireMetricHighRisk: 'nsarmoire.metric.highRisk',
  nsarmoireMetricDuplicateGroups: 'nsarmoire.metric.duplicateGroups',
  nsarmoireMetricCatalogItems: 'nsarmoire.metric.catalogItems',
  nsarmoireMetricCatalogCabinetItems: 'nsarmoire.metric.catalogCabinetItems',
  nsarmoireMetricCatalogSets: 'nsarmoire.metric.catalogSets',
  nsarmoireMetricCatalogModelGroups: 'nsarmoire.metric.catalogModelGroups',
  nsarmoireMetricCatalogDyes: 'nsarmoire.metric.catalogDyes',
  nsarmoireGeneratedAt: 'nsarmoire.field.generatedAt',
  nsarmoireSource: 'nsarmoire.field.source',
  nsarmoireCharacter: 'nsarmoire.field.character',
  nsarmoireCharacterWorld: 'nsarmoire.field.characterWorld',
  nsarmoireCharacterProfileKey: 'nsarmoire.field.characterProfileKey',
  nsarmoireCharacterRetainers: 'nsarmoire.field.characterRetainers',
  nsarmoireReadContainers: 'nsarmoire.field.readContainers',
  nsarmoireReadContainersMore: 'nsarmoire.field.readContainersMore',
  nsarmoireReadStatusRead: 'nsarmoire.field.readStatus.read',
  nsarmoireReadStatusUnread: 'nsarmoire.field.readStatus.unread',
  nsarmoireDetectedRetainers: 'nsarmoire.field.detectedRetainers',
  nsarmoireRetainerIndex: 'nsarmoire.field.retainerIndex',
  nsarmoireBasicStorageProgress: 'nsarmoire.field.basicStorageProgress',
  nsarmoireRetainerProgress: 'nsarmoire.field.retainerProgress',
  nsarmoireHelperEndpoint: 'nsarmoire.field.helperEndpoint',
  nsarmoireHelperCatalog: 'nsarmoire.field.helperCatalog',
  nsarmoireHelperCatalogReady: 'nsarmoire.field.helperCatalogReady',
  nsarmoireHelperCatalogMissing: 'nsarmoire.field.helperCatalogMissing',
  nsarmoireCharacterCurrentData: 'nsarmoire.character.currentData',
  nsarmoireCharacterNoSnapshot: 'nsarmoire.character.noSnapshot',
  nsarmoireCharacterStaticData: 'nsarmoire.character.staticData',
  nsarmoireCharacterUnknown: 'nsarmoire.character.unknown',
  nsarmoireCharacterWorldUnknown: 'nsarmoire.character.worldUnknown',
  nsarmoireCharacterGeneratedAtEmpty: 'nsarmoire.character.generatedAtEmpty',
  nsarmoireCharacterProfileKeyMissing: 'nsarmoire.character.profileKeyMissing',
  nsarmoireCharacterLocalProfileTitle: 'nsarmoire.character.localProfile.title',
  nsarmoireCharacterLocalProfileMessage: 'nsarmoire.character.localProfile.message',
  nsarmoireCharacterLocalProfilesEmpty: 'nsarmoire.character.localProfile.empty',
  nsarmoireCharacterLocalProfileCurrent: 'nsarmoire.character.localProfile.current',
  nsarmoireCharacterLocalProfileSwitch: 'nsarmoire.character.localProfile.switch',
  nsarmoireCharacterLocalProfileSwitching: 'nsarmoire.character.localProfile.switching',
  nsarmoireCharacterLocalProfileDelete: 'nsarmoire.character.localProfile.delete',
  nsarmoireCharacterLocalProfileDeleting: 'nsarmoire.character.localProfile.deleting',
  nsarmoireCharacterLocalProfileLoading: 'nsarmoire.character.localProfile.loading',
  nsarmoireCharacterLocalProfileError: 'nsarmoire.character.localProfile.error',
  nsarmoireCharacterLocalProfileUnavailable: 'nsarmoire.character.localProfile.unavailable',
  nsarmoireCharacterLocalProfileCachedAt: 'nsarmoire.character.localProfile.cachedAt',
  nsarmoireCharacterLocalProfileCount: 'nsarmoire.character.localProfile.count',
  nsarmoireCharacterLocalProfileSwitchSuccess: 'nsarmoire.character.localProfile.switchSuccess',
  nsarmoireCharacterLocalProfileDeleteSuccess: 'nsarmoire.character.localProfile.deleteSuccess',
  nsarmoireCharacterLocalProfileDeleteCurrentSuccess:
    'nsarmoire.character.localProfile.deleteCurrentSuccess',
  nsarmoireCharacterLocalProfileClearCurrent: 'nsarmoire.character.localProfile.clearCurrent',
  nsarmoireCharacterLocalProfileClearCurrentSuccess:
    'nsarmoire.character.localProfile.clearCurrentSuccess',
  nsarmoireCharacterRetainerFallback: 'nsarmoire.character.retainerFallback',
  nsarmoireSourceManualImport: 'nsarmoire.source.manualImport',
  nsarmoireSourceLocalHelper: 'nsarmoire.source.localHelper',
  nsarmoireSourceAsvelCompatible: 'nsarmoire.source.asvelCompatible',
  nsarmoireItemId: 'nsarmoire.field.itemId',
  nsarmoireUnknownItem: 'nsarmoire.field.unknownItem',
  nsarmoireDyes: 'nsarmoire.field.dyes',
  nsarmoireContainerInventory: 'nsarmoire.container.inventory',
  nsarmoireContainerSaddlebag: 'nsarmoire.container.saddlebag',
  nsarmoireContainerRetainer: 'nsarmoire.container.retainer',
  nsarmoireContainerArmoury: 'nsarmoire.container.armoury',
  nsarmoireContainerGlamourDresser: 'nsarmoire.container.glamourDresser',
  nsarmoireContainerArmoire: 'nsarmoire.container.armoire',
  nsarmoireContainerManual: 'nsarmoire.container.manual',
  nsglamourWorkspace: 'nsglamour.workspace.title',
  nsglamourTemplatePage: 'nsglamour.page.template',
  nsglamourEquipInfoPage: 'nsglamour.page.equipinfo',
  nsglamourImportPanel: 'nsglamour.panel.import',
  nsglamourEquipmentPanel: 'nsglamour.panel.equipment',
  nsglamourTemplateSettings: 'nsglamour.template.settings',
  nsglamourTemplateAuthor: 'nsglamour.template.author',
  nsglamourTemplateChange: 'nsglamour.template.change',
  nsglamourTemplateSelectorTitle: 'nsglamour.template.selector.title',
  nsglamourTemplateSelectorHint: 'nsglamour.template.selector.hint',
  nsglamourTemplateSelectorClose: 'nsglamour.template.selector.close',
  nsglamourTemplateSelectorFilter: 'nsglamour.template.selector.filter',
  nsglamourTemplateSelectorList: 'nsglamour.template.selector.list',
  nsglamourTemplateSelectorAll: 'nsglamour.template.selector.all',
  nsglamourTemplateSelectorEmpty: 'nsglamour.template.selector.empty',
  nsglamourTemplateSelectorCardTitle: 'nsglamour.template.selector.cardTitle',
  nsglamourTemplateAuthorLinks: 'nsglamour.template.authorLinks',
  nsglamourTemplateAuthorWebsite: 'nsglamour.template.author.website',
  nsglamourTemplateAuthorWeibo: 'nsglamour.template.author.weibo',
  nsglamourTemplateAuthorXiaohongshu: 'nsglamour.template.author.xiaohongshu',
  nsglamourTemplateAuthorDouyin: 'nsglamour.template.author.douyin',
  nsglamourTemplateTitleText: 'nsglamour.template.titleText',
  nsglamourTemplateCharacterName: 'nsglamour.template.characterName',
  nsglamourTemplateNameWorld: 'nsglamour.template.nameWorld',
  nsglamourTemplateName: 'nsglamour.template.name',
  nsglamourTemplateWorld: 'nsglamour.template.world',
  nsglamourTemplateSymbol: 'nsglamour.template.symbol',
  nsglamourTemplateDyeStyleOne: 'nsglamour.template.dyeStyleOne',
  nsglamourTemplateDyeStyleTwo: 'nsglamour.template.dyeStyleTwo',
  nsglamourTemplateEquipmentData: 'nsglamour.template.equipmentData',
  nsglamourTemplateImportLink: 'nsglamour.template.importLink',
  nsglamourTemplateImportTitle: 'nsglamour.template.import.title',
  nsglamourTemplateImportUrlLabel: 'nsglamour.template.import.urlLabel',
  nsglamourTemplateImportUrlPlaceholder: 'nsglamour.template.import.urlPlaceholder',
  nsglamourTemplateImportHint: 'nsglamour.template.import.hint',
  nsglamourTemplateImportSubmit: 'nsglamour.template.import.submit',
  nsglamourTemplateImportClose: 'nsglamour.template.import.close',
  nsglamourTemplateLayoutLanguage: 'nsglamour.template.layoutLanguage',
  nsglamourTemplateLanguageCurrentEdit: 'nsglamour.template.language.currentEdit',
  nsglamourTemplateLanguageOutput: 'nsglamour.template.language.output',
  nsglamourTemplateClearDraft: 'nsglamour.template.clearDraft',
  nsglamourTemplateCanvas: 'nsglamour.template.canvas',
  nsglamourTemplateSaveImage: 'nsglamour.template.saveImage',
  nsglamourTemplateUploadImage: 'nsglamour.template.image.upload',
  nsglamourTemplateRecentImages: 'nsglamour.template.image.recent',
  nsglamourTemplateRecentImagesEmpty: 'nsglamour.template.image.recent.empty',
  nsglamourTemplateRecentImagesClear: 'nsglamour.template.image.recent.clear',
  nsglamourTemplateRecentImageFallback: 'nsglamour.template.image.recent.fallback',
  nsglamourTemplateCropTitle: 'nsglamour.template.crop.title',
  nsglamourTemplateCropHint: 'nsglamour.template.crop.hint',
  nsglamourTemplateCropCanvas: 'nsglamour.template.crop.canvas',
  nsglamourTemplateCropZoom: 'nsglamour.template.crop.zoom',
  nsglamourTemplateCropZoomPercent: 'nsglamour.template.crop.zoomPercent',
  nsglamourTemplateCropCancel: 'nsglamour.template.crop.cancel',
  nsglamourTemplateCropReset: 'nsglamour.template.crop.reset',
  nsglamourTemplateCropApply: 'nsglamour.template.crop.apply',
  nsglamourCopyPanel: 'nsglamour.panel.copy',
  nsglamourRecentPanel: 'nsglamour.panel.recent',
  nsglamourImportLinkLabel: 'nsglamour.import.link.label',
  nsglamourImportLinkPlaceholder: 'nsglamour.import.link.placeholder',
  nsglamourImportReadLink: 'nsglamour.import.readLink',
  nsglamourImportTextLabel: 'nsglamour.import.text.label',
  nsglamourImportTextPlaceholder: 'nsglamour.import.text.placeholder',
  nsglamourImportSourceLocale: 'nsglamour.import.sourceLocale',
  nsglamourImportParseText: 'nsglamour.import.parseText',
  nsglamourClearDraft: 'nsglamour.action.clearDraft',
  nsglamourSaveConfig: 'nsglamour.action.saveConfig',
  nsglamourCopyAction: 'nsglamour.action.copy',
  nsglamourCopyOutput: 'nsglamour.copy.output',
  nsglamourCopyFormat: 'nsglamour.copy.format',
  nsglamourCopyFormatOne: 'nsglamour.copy.format.one',
  nsglamourCopyFormatTwo: 'nsglamour.copy.format.two',
  nsglamourCopyFormatThree: 'nsglamour.copy.format.three',
  nsglamourCopyFormatFour: 'nsglamour.copy.format.four',
  nsglamourCopyFormatCustom: 'nsglamour.copy.format.custom',
  nsglamourCopyTemplate: 'nsglamour.copy.template',
  nsglamourCopyResetTemplate: 'nsglamour.copy.resetTemplate',
  nsglamourEquipmentLanguage: 'nsglamour.equipment.language',
  nsglamourEquipmentDyes: 'nsglamour.equipment.dyes',
  nsglamourEquipmentUndyeable: 'nsglamour.equipment.undyeable',
  nsglamourEquipmentDyeIgnored: 'nsglamour.equipment.dyeIgnored',
  nsglamourEquipmentDyeSlot: 'nsglamour.equipment.dyeSlot',
  nsglamourEquipmentDyeSlotNumber: 'nsglamour.equipment.dyeSlotNumber',
  nsglamourEquipmentDyeSearchPlaceholder: 'nsglamour.equipment.dyeSearch.placeholder',
  nsglamourEquipmentDyeSearchEmpty: 'nsglamour.equipment.dyeSearch.empty',
  nsglamourEquipmentDyeLoading: 'nsglamour.equipment.dyeSearch.loading',
  nsglamourEquipmentDyeLoadError: 'nsglamour.equipment.dyeSearch.error',
  nsglamourEquipmentSearchPlaceholder: 'nsglamour.equipment.search.placeholder',
  nsglamourEquipmentSearchEmpty: 'nsglamour.equipment.search.empty',
  nsglamourEquipmentSearchError: 'nsglamour.equipment.search.error',
  nsglamourEquipmentDelete: 'nsglamour.equipment.delete',
  nsglamourEquipmentDeleteSymbol: 'nsglamour.equipment.delete.symbol',
  nsglamourEquipmentSwitchCandidate: 'nsglamour.equipment.switchCandidate',
  nsglamourEquipmentSwitchCandidateSymbol: 'nsglamour.equipment.switchCandidate.symbol',
  nsglamourConfigNamePrompt: 'nsglamour.recent.configName.prompt',
  nsglamourRecentClear: 'nsglamour.recent.clear',
  nsglamourRecentDelete: 'nsglamour.recent.delete',
  nsglamourRecentDeleteNamed: 'nsglamour.recent.deleteNamed',
  nsglamourRecentDeleteSymbol: 'nsglamour.recent.delete.symbol',
  nsglamourRecentEmpty: 'nsglamour.recent.empty',
  nsglamourRecentMeta: 'nsglamour.recent.meta',
  nsglamourRecentUnnamed: 'nsglamour.recent.unnamed',
  nsglamourWarnings: 'nsglamour.warnings.title',
  nsglamourStatusIdle: 'nsglamour.status.idle',
  nsglamourStatusReadingLink: 'nsglamour.status.readingLink',
  nsglamourStatusParsingText: 'nsglamour.status.parsingText',
  nsglamourStatusReadingConfig: 'nsglamour.status.readingConfig',
  nsglamourStatusImportError: 'nsglamour.status.importError',
  nsglamourStatusLinkRequired: 'nsglamour.status.linkRequired',
  nsglamourStatusUnsupportedLink: 'nsglamour.status.unsupportedLink',
  nsglamourStatusTextRequired: 'nsglamour.status.textRequired',
  nsglamourStatusInvalidLocalFile: 'nsglamour.status.invalidLocalFile',
  nsglamourStatusFileTooLarge: 'nsglamour.status.fileTooLarge',
  nsglamourStatusNoConfigToSave: 'nsglamour.status.noConfigToSave',
  nsglamourStatusConfigSaved: 'nsglamour.status.configSaved',
  nsglamourStatusConfigRestored: 'nsglamour.status.configRestored',
  nsglamourStatusRecentDeleted: 'nsglamour.status.recentDeleted',
  nsglamourStatusRecentCleared: 'nsglamour.status.recentCleared',
  nsglamourStatusCopied: 'nsglamour.status.copied',
  nsglamourStatusCopyError: 'nsglamour.status.copyError',
  nsglamourStatusCopyEmpty: 'nsglamour.status.copyEmpty',
  nsglamourLocaleZh: 'nsglamour.locale.zh',
  nsglamourLocaleEn: 'nsglamour.locale.en',
  nsglamourLocaleJa: 'nsglamour.locale.ja',
  nsglamourLocaleKo: 'nsglamour.locale.ko',
  nsglamourLocaleTc: 'nsglamour.locale.tc',
  nsglamourLocaleFr: 'nsglamour.locale.fr',
  nsglamourLocaleDe: 'nsglamour.locale.de',
  nsplatePortrait: 'nsplate.tab.portrait',
  nsplateNameplate: 'nsplate.tab.nameplate',
  nsplateInfo: 'nsplate.tab.info',
  nsplateInfoPreset: 'nsplate.info.preset',
  nsplateInfoFields: 'nsplate.info.fields',
  nsplateInfoLayerShow: 'nsplate.info.layer.show',
  nsplateInfoLayerHide: 'nsplate.info.layer.hide',
  nsplateConfig: 'nsplate.panel.config',
  nsplateAssets: 'nsplate.panel.assets',
  nsplatePresets: 'nsplate.panel.presets',
  nsplateCurrentCombination: 'nsplate.panel.currentCombination',
  nsplateLayerOrder: 'nsplate.panel.layerOrder',
  nsplateLayerOrderCustomPortraitPopout: 'nsplate.layerOrder.customPortraitPopout',
  nsplateLayerOrderInfoLayers: 'nsplate.layerOrder.infoLayers',
  nsplateLayerOrderEnabled: 'nsplate.layerOrder.enabled',
  nsplateLayerOrderNotEnabled: 'nsplate.layerOrder.notEnabled',
  nsplateLayerOrderMoveUp: 'nsplate.layerOrder.moveUp',
  nsplateLayerOrderMoveDown: 'nsplate.layerOrder.moveDown',
  nsplatePortraitAssets: 'nsplate.panel.portraitAssets',
  nsplateNameplateAssets: 'nsplate.panel.nameplateAssets',
  nsplateCustomPortrait: 'nsplate.panel.customPortrait',
  nsplatePortraitSide: 'nsplate.portraitSide.title',
  nsplatePortraitSideLeft: 'nsplate.portraitSide.left',
  nsplatePortraitSideRight: 'nsplate.portraitSide.right',
  nsplateCustomPortraitUpload: 'nsplate.customPortrait.upload',
  nsplateCustomPortraitClear: 'nsplate.customPortrait.clear',
  nsplateCustomPortraitClearConfirm: 'nsplate.customPortrait.clearConfirm',
  nsplateCustomPortraitInput: 'nsplate.customPortrait.input',
  nsplateCustomPortraitError: 'nsplate.customPortrait.error',
  nsplateCustomPortraitCropTitle: 'nsplate.customPortrait.crop.title',
  nsplateCustomPortraitCropCanvas: 'nsplate.customPortrait.crop.canvas',
  nsplateCustomPortraitCropMode: 'nsplate.customPortrait.crop.mode',
  nsplateCustomPortraitCropModeStandard: 'nsplate.customPortrait.crop.mode.standard',
  nsplateCustomPortraitCropModePopout: 'nsplate.customPortrait.crop.mode.popout',
  nsplateCustomPortraitCropZoom: 'nsplate.customPortrait.crop.zoom',
  nsplateCustomPortraitCropSplit: 'nsplate.customPortrait.crop.split',
  nsplateCustomPortraitCropCancel: 'nsplate.customPortrait.crop.cancel',
  nsplateCustomPortraitCropApply: 'nsplate.customPortrait.crop.apply',
  nsplateWorkbenchActions: 'nsplate.action.menu',
  nsplateClearAllSelections: 'nsplate.action.clearAllSelections',
  nsplateClearAllSelectionsConfirm: 'nsplate.action.clearAllSelectionsConfirm',
  nsplateImportConfig: 'nsplate.config.import',
  nsplateImportConfigInput: 'nsplate.config.importInput',
  nsplateImportConfigSuccess: 'nsplate.config.importSuccess',
  nsplateImportConfigPartial: 'nsplate.config.importPartial',
  nsplateImportConfigUnsupported: 'nsplate.config.importUnsupported',
  nsplateImportConfigError: 'nsplate.config.importError',
  nsplatePasteConfig: 'nsplate.config.paste',
  nsplatePasteConfigError: 'nsplate.config.pasteError',
  nsplateCopyConfig: 'nsplate.config.copy',
  nsplateExportConfig: 'nsplate.config.export',
  nsplateCopyConfigSuccess: 'nsplate.config.copySuccess',
  nsplateCopyConfigError: 'nsplate.config.copyError',
  nsplateExportPng: 'nsplate.export.png',
  nsplateExportJpg: 'nsplate.export.jpg',
  nsplateExportLayeredZip: 'nsplate.export.layeredZip',
  nsplateExportScale2x: 'nsplate.export.scale2x',
  nsplateExportError: 'nsplate.export.error',
  nsplateExportNoLayers: 'nsplate.export.error.noLayers',
  nsplateExportLayeredZipError: 'nsplate.export.error.layeredZip',
  nsplateCanvasEditing: 'nsplate.canvas.editing',
  nsplateCanvasSelectedPreset: 'nsplate.canvas.selectedPreset',
  nsplateCanvasSelectedLayers: 'nsplate.canvas.selectedLayers',
  nsplateCanvasLayers: 'nsplate.canvas.layers',
  nsplateCanvasSelectionStatus: 'nsplate.canvas.selectionStatus',
  nsplateCanvasAria: 'nsplate.canvas.aria',
  nsplateCanvasViewportToolbar: 'nsplate.canvas.viewportToolbar',
  nsplateCanvasClearToolbar: 'nsplate.canvas.clearToolbar',
  nsplateCanvasZoomOut: 'nsplate.canvas.zoomOut',
  nsplateCanvasZoomIn: 'nsplate.canvas.zoomIn',
  nsplateCanvasZoomLabel: 'nsplate.canvas.zoomLabel',
  nsplateCanvasResetView: 'nsplate.canvas.resetView',
  nsplateResizeConfigPanel: 'nsplate.resize.configPanel',
  nsplateCategoryPortraitBackground: 'nsplate.category.portraitBackground',
  nsplateCategoryPortraitDecorFrame: 'nsplate.category.portraitDecorFrame',
  nsplateCategoryPortraitDecoration: 'nsplate.category.portraitDecoration',
  nsplateCategoryPortraitFrame: 'nsplate.category.portraitFrame',
  nsplateCategoryNameplateBase: 'nsplate.category.nameplateBase',
  nsplateCategoryNameplateColor: 'nsplate.category.nameplateColor',
  nsplateCategoryNameplatePattern: 'nsplate.category.nameplatePattern',
  nsplateCategoryNameplateFrame: 'nsplate.category.nameplateFrame',
  nsplateCategoryNameplateTopDecor: 'nsplate.category.nameplateTopDecor',
  nsplateCategoryNameplateBottomDecor: 'nsplate.category.nameplateBottomDecor',
  nsplateCategoryNameplateDecoration: 'nsplate.category.nameplateDecoration',
  nsplateCategoryNameplateDecorationAlt: 'nsplate.category.nameplateDecorationAlt',
  styleLabPixelTone: 'styleLab.pixelTone',
  styleLabFontMode: 'styleLab.fontMode',
  styleLabTitle: 'styleLab.title',
  styleLabSampleLead: 'styleLab.sampleLead',
  styleLabPrimary: 'styleLab.primary',
  styleLabAction: 'styleLab.action',
  styleLabDefault: 'styleLab.default',
  styleLabWindowSample: 'styleLab.windowSample',
  styleLabPalette: 'styleLab.palette',
  styleLabProgress: 'styleLab.progress',
  styleLabPopupMenuSample: 'styleLab.popupMenuSample',
  styleLabPopupWindowSample: 'styleLab.popupWindowSample',
  styleLabPopupNavigationSample: 'styleLab.popupNavigationSample',
  styleLabFfxivChildren: 'styleLab.ffxivChildren',
  styleLabOcChildren: 'styleLab.ocChildren',
  styleLabWorkbenchSample: 'styleLab.workbenchSample',
  styleLabWorkbenchToolbar: 'styleLab.workbenchToolbar',
  styleLabWorkbenchSidebar: 'styleLab.workbenchSidebar',
  styleLabWorkbenchCanvas: 'styleLab.workbenchCanvas',
  styleLabWorkbenchInspector: 'styleLab.workbenchInspector',
  styleLabWorkbenchMeters: 'styleLab.workbenchMeters',
  styleLabToolbarSample: 'styleLab.toolbarSample',
  styleLabCommonToolbarPreview: 'styleLab.commonToolbarPreview',
  styleLabCommonTabsPreview: 'styleLab.commonTabsPreview',
  styleLabFormalComponents: 'styleLab.formalComponents',
  styleLabFormalControls: 'styleLab.formalControls',
  styleLabFormalStates: 'styleLab.formalStates',
  styleLabToolCardSamples: 'styleLab.toolCardSamples',
  styleLabDecorativePixels: 'styleLab.decorativePixels',
  styleLabAllPixels: 'styleLab.allPixels',
  styleLabCurrentPixel: 'styleLab.currentPixel',
  styleLabLightPixel: 'styleLab.lightPixel',
  styleLabCyberNight: 'styleLab.cyberNight',
  styleLabTools: 'styleLab.tools',
  styleLabEquipmentPanel: 'styleLab.equipmentPanel',
  styleLabTemplate: 'styleLab.template',
  styleLabAssets: 'styleLab.assets',
  styleLabLayers: 'styleLab.layers',
  styleLabTitleField: 'styleLab.titleField',
  styleLabCharacter: 'styleLab.character',
  styleLabEquipment: 'styleLab.equipment',
  styleLabBackground: 'styleLab.background',
  styleLabInspector: 'styleLab.inspector',
  styleLabLanguage: 'styleLab.language',
  styleLabReady: 'styleLab.ready',
  styleLabName: 'styleLab.name',
  styleLabModule: 'styleLab.module',
  styleLabToolBadge: 'styleLab.toolBadge',
  styleLabStatusPanel: 'styleLab.statusPanel',
  styleLabAppField: 'styleLab.appField',
  styleLabAppToolbar: 'styleLab.appToolbar',
  styleLabAppStatus: 'styleLab.appStatus',
  styleLabIconLab: 'styleLab.iconLab',
  styleLabIconTextBar: 'styleLab.iconTextBar',
  styleLabIconOnlyButtons: 'styleLab.iconOnlyButtons',
  styleLabTextIconButtons: 'styleLab.textIconButtons',
  styleLabIconMenuSample: 'styleLab.iconMenuSample',
  styleLabIconSource: 'styleLab.iconSource',
  styleLabIconHome: 'styleLab.icon.home',
  styleLabIconMenu: 'styleLab.icon.menu',
  styleLabIconConfig: 'styleLab.icon.config',
  styleLabIconSearch: 'styleLab.icon.search',
  styleLabIconDownload: 'styleLab.icon.download',
  styleLabIconImage: 'styleLab.icon.image',
  styleLabIconFolder: 'styleLab.icon.folder',
  styleLabIconFavorite: 'styleLab.icon.favorite',
  styleLabIconLanguage: 'styleLab.icon.language',
  styleLabNotebookLab: 'styleLab.notebookLab',
  styleLabNotebookCard: 'styleLab.notebook.card',
  styleLabNotebookFold: 'styleLab.notebook.fold',
  styleLabNotebookComment: 'styleLab.notebook.comment',
  styleLabNotebookRuleTitle: 'styleLab.notebook.rule.title',
  styleLabNotebookRuleValue: 'styleLab.notebook.rule.value',
  styleLabNotebookRuleFold: 'styleLab.notebook.rule.fold',
  styleLabMetaText: 'styleLab.meta.text',
  styleLabMetaMaterial: 'styleLab.meta.material',
  styleLabMetaCurrentGroup: 'styleLab.meta.currentGroup',
  styleLabMetaPortraitBackground: 'styleLab.meta.portraitBackground',
  styleLabMetaPortraitFrame: 'styleLab.meta.portraitFrame',
  styleLabMetaPortraitDecoration: 'styleLab.meta.portraitDecoration',
  styleLabMetaNameplateBacking: 'styleLab.meta.nameplateBacking',
  styleLabMetaGray: 'styleLab.meta.gray',
  styleLabMetaGlow: 'styleLab.meta.glow',
  styleLabMetaUnselected: 'styleLab.meta.unselected',
  styleLabMetaNewColor: 'styleLab.meta.newColor',
  styleLabSkinName: 'styleLab.skinName'
} as const

export const placeholderCopyKey = textKeys.placeholder

function defaultText(key: string): string {
  return uiMessages[key]?.['zh-CN'] ?? key
}

// Deprecated compatibility exports for stale Vite HMR modules from the pre-localization scaffold.
// New code must use textKeys + useLocale().t(key) instead of these static fallbacks.
export const placeholderCopy = defaultText(textKeys.placeholder)

export const siteLabels = {
  menu: defaultText(textKeys.menu),
  menuCommand: defaultText(textKeys.menuCommand),
  homeCommand: defaultText(textKeys.homeCommand),
  config: defaultText(textKeys.config),
  configCommand: defaultText(textKeys.configCommand),
  themeMode: defaultText(textKeys.themeMode),
  day: defaultText(textKeys.day),
  dayCommand: defaultText(textKeys.dayCommand),
  night: defaultText(textKeys.night),
  nightCommand: defaultText(textKeys.nightCommand),
  ffxivWorkshop: defaultText(textKeys.ffxivWorkshop),
  ffxivWorkshopShort: defaultText(textKeys.ffxivWorkshopShort),
  about: defaultText(textKeys.about),
  aboutCommand: defaultText(textKeys.aboutCommand),
  home: defaultText(textKeys.home)
} as const

export const siteMeta = {
  zhNameKey: textKeys.siteZhName,
  enNameKey: textKeys.siteEnName,
  titleKey: textKeys.siteTitle,
  descriptionKey: textKeys.siteDescription
} as const

export const siteRoutes = {
  home: '/',
  ffxiv: '/ffxiv',
  glamour: '/ffxiv/glamour',
  glamourTemplate: '/ffxiv/glamour/template',
  glamourEquipInfo: '/ffxiv/glamour/equipinfo',
  plate: '/ffxiv/plate',
  armoire: '/ffxiv/armoire',
  silence: '/silence',
  silenceAngel: '/silence/angel',
  silenceGlitch: '/silence/glitch',
  about: '/about'
} as const satisfies Record<string, RoutePath>

export const siteLocaleOptions: SiteLocaleOption[] = [
  { locale: 'zh-CN', labelKey: textKeys.localeZhLabel, commandKey: textKeys.localeZhCommand },
  { locale: 'ja', labelKey: textKeys.localeJaLabel, commandKey: textKeys.localeJaCommand },
  { locale: 'ko', labelKey: textKeys.localeKoLabel, commandKey: textKeys.localeKoCommand },
  { locale: 'en', labelKey: textKeys.localeEnLabel, commandKey: textKeys.localeEnCommand }
]

export const homeNavItems: NavItem[] = [
  {
    id: 'ffxiv',
    labelKey: textKeys.ffxivWorkshop,
    route: siteRoutes.ffxiv,
    variant: 'primary'
  },
  {
    id: 'silence',
    labelKey: textKeys.silence,
    commandKey: textKeys.silenceCommand,
    route: siteRoutes.silence
  },
  {
    id: 'about',
    labelKey: textKeys.about,
    commandKey: textKeys.aboutCommand,
    route: siteRoutes.about
  }
]

export const siteCategories: SiteCategory[] = [
  {
    id: 'ffxiv',
    titleKey: textKeys.ffxivWorkshop,
    shortTitleKey: textKeys.ffxivWorkshopShort,
    kickerKey: textKeys.placeholder,
    descriptionKey: textKeys.placeholder,
    route: siteRoutes.ffxiv
  },
  {
    id: 'silence',
    titleKey: textKeys.silence,
    shortTitleKey: textKeys.silence,
    kickerKey: textKeys.placeholder,
    descriptionKey: textKeys.placeholder,
    route: siteRoutes.silence
  }
]

export const silenceGroups: SilenceGroupEntry[] = [
  {
    id: 'angel',
    titleKey: textKeys.silenceAngel,
    route: siteRoutes.silenceAngel,
    summaryKey: textKeys.placeholder,
    statusLabelKey: textKeys.statusWip
  },
  {
    id: 'glitch',
    titleKey: textKeys.silenceGlitch,
    route: siteRoutes.silenceGlitch,
    summaryKey: textKeys.placeholder,
    statusLabelKey: textKeys.statusWip
  }
]

export const ffxivTools: ToolEntry[] = [
  {
    id: 'glamour',
    titleKey: textKeys.glamourTitle,
    projectName: 'NSGlamour',
    route: siteRoutes.glamour,
    summaryKey: textKeys.placeholder,
    sourcePath: '../NSGlamour',
    apiBase: '/api/glamour',
    devPort: 8765,
    statusLabelKey: textKeys.placeholder
  },
  {
    id: 'plate',
    titleKey: textKeys.plateTitle,
    projectName: 'NSPlate',
    route: siteRoutes.plate,
    summaryKey: textKeys.placeholder,
    sourcePath: '../NSPortable',
    apiBase: '/api/plate',
    devPort: 3456,
    statusLabelKey: textKeys.placeholder
  },
  {
    id: 'armoire',
    titleKey: textKeys.armoireTitle,
    projectName: 'NSArmoire',
    route: siteRoutes.armoire,
    summaryKey: textKeys.placeholder,
    sourcePath: 'docs/ARMOIRE_PLAN.md',
    apiBase: '/api/armoire',
    devPort: 8015,
    statusLabelKey: textKeys.placeholder
  }
]

export function getCategory(id: string): SiteCategory | undefined {
  return siteCategories.find((category) => category.id === id)
}

export function getFfxivTool(id: string): ToolEntry | undefined {
  return ffxivTools.find((tool) => tool.id === id)
}

export function getRequiredFfxivTool(id: string): ToolEntry {
  const tool = getFfxivTool(id)

  if (!tool) {
    throw new Error(`Unknown FFXIV tool: ${id}`)
  }

  return tool
}

export function formatDocumentTitle(
  title: string | undefined,
  siteName: string,
  siteTitle: string
): string {
  if (!title || title === siteName) {
    return siteTitle
  }

  return `${title} - ${siteName}`
}
